drop table if exists score CASCADE;

create table score
(
    id         int generated by default as identity,
    name       varchar(20),
    score      BIGINT,
    created_at TIMESTAMP default CURRENT_TIMESTAMP
        primary key (id)
);