drop table if exists score CASCADE;

create table score
(
    id         int generated by default as identity,
    name       varchar(20),
    score      BIGINT,
    created_at TIMESTAMP default CURRENT_TIMESTAMP
        primary key (id)
);


---------------------

insert into score(name, score)
values (?, ?)

----------------------

select *
from score
ORDER BY score DESC, created_at ASC LIMIT 30")